### PR TITLE
Support min version when adding in add_or_update

### PR DESCRIPTION
**Pull request by algrs**
This was crashing the script that builds def transfers, as there was a file we were trying to `add_or_update(min_version='1.1.0')` that existed as `1.0.0` on s3 but wasn't in the manifest, so the add branch was being called. Since the add branch didn't support `min_version`, it was trying to write the default of `1.0.0` and crashing because that already exists.

### CODE REVIEW

**Comment by algrs** [comment]
Needed for https://github.com/bodylabs/core/pull/563

**Comment by dlsmith** [comment]
Hm, but that file really shouldn't exist. I.e., every file in the versioned assets bucket should be noted in the manifest. This allowed us to catch a cleanup bug.

**Comment by algrs** [comment]
I disagree, actually -- the bucket is intended as immutable and every branch can have its own manifest, so it's inevitable that there should be items in the bucket that are not in some particular copy of the manifest. The bucket has to be the final source of truth as to what files exist.

Also, the issue here is not that the particular file should not exist, it's that we're not honoring `min_version`, so we're trying to write a file at 1.0.0 in a function call that explicitly asked to write it at no less than 1.1. If I call
```py
add_or_update('/foo.txt', file, min_version='1.1')
```
and get a `s3://bucket/foo.1.0.0.txt` that's clearly a bug.

**Comment by algrs** [comment]
Thanks @dlsmith

**Pull request merged**
